var faq = {
	"what is insurance" : "Insurance is a contract usually between a large financial institution that offers fixed protection to another person, institution or entity against a possible future loss in return of a predetermined premium. Insurance is a Risk management tool that is taken as a precautionary measure against future risks that may or may not happen.",
	"Is car insurance mandatory ?":"Yes, under provisions of the India Motor Vehicles Act 1988 car insurance is mandatory in India. Any vehicle used for social, domestic and pleasure purpose and for the insured’s business or profession.",
	"What are the different types of car insurance ?" : "Types of car insurance- <br>• Liability only policy -This covers “Third Party Liability” for bodily injury and/ or death and property damage .Personal accident cover for owner-driver is also included. <br>• Comprehensive Package Policy – This covers third party liability, damage to own car and has various features as a package. <br>• Zero Depreciation Policy- This cover helps you to avail full claim without any deduction for depreciation on the value of parts replaced.",
	"What is a policy?":"Policy is a stamped document which provides an evidence of the contract of the insurance between the insurer and insured.",
	"What does comprehensive package car insurance cover? ":"Comprehensive car insurance covers damage to own car along with third party liability. It allows safety cover against damage or loss to car against. <br>• Fire, explosion, self ignition, or lightning. <br>• Natural disasters like floods, hurricanes and storms, earthquakes, Landslide etc. <br>• Burglary, housebreaking or theft. <br>• Riot, strike or terrorist activity. <br>• Accidents. <br>• Malicious act. <br>• Whilst in transit by road, rail, inland, waterway, lift, elevator or air.",
	"Does my vehicle need to be inspected before insurance?":"The vehicle might need to be inspected by the insurance company representative if <br>• There is a break in insurance. <br>• There is a change in type of policy. <br>• There is a change in policy ownership. <br>• You have added accessories that you want insured. <br>• If your are installing CNG/LPG kit in your vehicle, one has to get the kit endorsed in his Rc (Registration Certificate) book by the RTO (Road transport office). Additional premium is payable for the vehicle with LPG/CNG kit.",
	"What is Premium?":"Premium is the financial cost of an insurance policy paid either as Lumpsum or in several installments during the period covered by the policy.",
	"How is my car evaluated by insurance companies?":"The Premium of vehicle insurance depends upon <br>• Insured Declared Value (IDV). <br>• Vehicle Make & Model. <br>• Place of registration (Zone). <br>• Additional covers taken. <br>• Registration year of the vehicle.",
	"What is IDV or insured declared value?":"IDV or the insured declared value of the vehicle is the value of the vehicle that it is insured for. It is fixed every year at the commencement of each policy period. It is arrived at taking into account the manufacturer’s listed selling price of the brand and model, accessories if any that are not included in the manufacturers list and annual depreciation. For vehicles aged over 5 years of age and of obsolete models the IDV is a value agreed upon between the owner and insurance company.",
	"Which discounts can I avail for car insurance?":"Discounts available for the Premium of car insurance <br>• Voluntary Deductible. <br>• No Claim Bonus.  <br>• Automobile Association Membership. <br>• Installing anti theft devices. <br>• Discount for Vintage Cars.",
	"What happens if someone else is driving at the time of the accident?":"Repairs invoice or payment receipt."
}

Cars = {
	"Hyundai": ["Creta 1.6 S",
		"Eon D-Lite +",
		"Verna VTVT SX 1.6",
		"Elite i20 Era 1.2",
		"Elite i20 Magna 1.2",
		"Fluidic Verna 1.6 VTVT S AT",
		"Xcent Base 1.2",
		"i10 Era",
		"i20 Asta 1.4 AT",
		"Sonata 2.7 V6",
		"Verna Transform 1.6 VTVT",
		"Verna Transform 1.6 SX VTVT",
		"Santro Xing GLS AT",
		"Elantra 1.8 S",
		"Elantra 1.8 SX MT",
		"Eon Era + (Petrol)",
		"Fluidic Verna 1.6 VTVT S",
		"Grand i10 Era 1.2 Kappa VTVT",
		"Grand i10 Magna 1.2 Kappa VTVT",
		"i20 Active 1.2 SX",
		"i10 Sportz 1.2 AT",
		"i20 Era 1.2",
		"Sonata 2.4 GDi AT",
		"Eon 1.0 Kappa Magna +",
		"Accent GTX - Tornado",
		"Sonata Embera AT",
		"Creta 1.6 SX Plus MT",
		"Eon Magna + (Petrol)",
		"Fluidic Verna 1.4 VTVT",
		"Grand i10 Asta 1.2 Kappa VTVT",
		"i10 Sportz 1.1 iRDE2",
		"Sonata GLS",
		"Sonata GOLD",
		"Verna VTVT 1.6",
		"Verna XXi",
		"Santro Xing GL (Petrol)",
		"i20 Sportz 1.4 AT (Petrol)",
		"Elite i20 Asta 1.2",
		"i20 Magna 1.2",
		"Xcent SX AT 1.2",
		"Grand i10 Sportz 1.2 Kappa VTVT",
		"i10 Era 1.1 iRDE2",
		"i20 Active 1.2",
		"Accent GLS 1.6",
		"Elantra GLS",
		"i10 D-Lite",
		"i10 Asta 1.2",
		"i20 Asta 1.2",
		"i20 Asta 1.2 with AVN",
		"Santro Xing XL AT eRLX",
		"Santro Xing XO eRLX",
		"Accent Executive (Petrol)",
		"Verna Fluidic 1.4 VTVT GL",
		"Elite i20 Sportz 1.2",
		"Accent GLE",
		"i10 Asta 1.2 AT with Sunroof",
		"i10 Magna",
		"Sonata 2.4 GDi MT",
		"i20 Active 1.2 S",
		"Xcent S 1.2",
		"Accent GLE",
		"Getz Prime 1.1 GVS",
		"Getz Prime 1.3 GLS",
		"i10 Magna 1.2 AT",
		"Verna Fluidic 1.6 VTVT",
		"Verna Fluidic VTVT 1.6 EX AT",
		"Elantra 1.8 SX AT",
		"Eon D-Lite",
		"Fluidic Verna 1.6 VTVT SX",
		"Xcent SX 1.2",
		"Accent Viva",
		"Elantra GT",
		"Getz Prime 1.3 GLX",
		"i10 Asta 1.2 AT with Sunroof",
		"i20 Asta 1.4 CRDI",
		"Sonata S 20",
		"Santro Xing GLS (Petrol)",
		"i10 Magna 1.2",
		"Santro Xing XL eRLX",
		"Sonata Embera MT",
		"Sonata Embera 2.0 CRDi",
		"Verna Xi",
		"Santro Xing GL Plus (Petrol)",
		"Eon Sportz",
		"Accent GLS 1.6",
		"Getz Prime 1.3 GVS",
		"Getz Prime 1.1 GLE",
		"Santro Xing XK eRLX",
		"Grand i10 Asta AT 1.2 Kappa VTVT",
		"i10 1.1L iRDE Magna Special Edition",
		"Sonata Transform 2.4 VTVT",
		"Verna i",
		"Santro Xing Non-AC",
		"Verna Fluidic 1.4 VTVT CX",
		"i10 Sportz 1.2",
		"i20 Sportz 1.2",
		"Verna Fluidic 1.6 VTVT EX",
		"Verna Fluidic 1.6 VTVT SX AT",
		"Elantra 1.6 Base",
		"Elantra 1.6 SX MT",
		"i20 Active 1.4 S",
		"i20 Magna 1.4 CRDI",
		"Creta 1.4 S",
		"Fluidic Verna 1.6 CRDi SX AT",
		"Verna Transform 1.5 CRDi",
		"Verna Fluidic CRDi 1.6 EX AT",
		"Verna VGT CRDi",
		"Santa Fe 4 WD MT",
		"Elite i20 Sportz 1.4",
		"i20 Asta 1.4 CRDI",
		"Sonata Transform 2.0 CRDi M/T",
		"Verna Fluidic 1.6 CRDi",
		"Fluidic Verna 1.4 CRDi",
		"Xcent Base 1.1 CRDi",
		"Sonata Embera 2.0 CRDi AT",
		"Verna CRDI VGT 1.5",
		"Verna Fluidic 1.4 CRDi GL",
		"Creta 1.4 Base",
		"Xcent SX 1.1 CRDi",
		"Sonata Transform 2.0 CRDi A/T",
		"Elantra 1.6 SX AT",
		"Fluidic Verna 1.6 CRDi S",
		"Santa Fe 4 WD AT",
		"Verna Transform 1.5 SX CRDi",
		"Elantra 1.6 S MT",
		"Fluidic Verna 1.6 CRDi SX",
		"Grand i10 Asta 1.1 CRDi",
		"Verna Transform 1.5 SX AT CRDi",
		"Verna Fluidic 1.4 CRDi EX",
		"Verna Fluidic 1.4 CRDi CX",
		"Creta 1.6 SX",
		"Elite i20 Era 1.4 CRDI",
		"i20 Active 1.4",
		"i20 Era 1.4 CRDI",
		"Elite i20 Magna 1.4 CRDI",
		"Fluidic Verna 1.6 VTVT S",
		"Grand i10 Sportz 1.1 CRDi",
		"i20 Sportz 1.4 (Diesel)",
		"Santa Fe 2 WD AT",
		"Xcent S 1.1 CRDi",
		"Verna CRDI VGT SX AT 1.5",
		"Grand i10 Magna 1.1 CRDi",
		"Elantra CRDi",
		"Tucson CRDi",
		"Verna Fluidic 1.6 CRDi EX",
		"Elite i20 Asta 1.4 CRDI",
		"i20 Active 1.4 SX",
		"Accent CRDi",
		"Accent Viva CRDi",
		"Getz Prime 1.5 GVS CRDi",
		"Creta 1.6 SX Plus AT",
		"Grand i10 Era 1.1 CRDi",
		"Santa Fe 2 WD MT",
		"Grand i10 Magna 1.0 Kappa VTVT",
		"Santro Xing GL Plus (LPG)",
		"Santro Xing GLS (LPG)",
		"Santro Xing GL (LPG)",
		"Eon Magna + (LPG)",
		"Accent Executive (LPG)",
		"Grand i10 Magna 1.0 Kappa VTVT",
		"i10 Sportz 1.1 (LPG)",
		"Santro Xing GLS (CNG)",
		"Eon Era + (LPG)",
		"Santro Xing GL Plus (LPG)",
		"Santro Xing GLS (CNG)",
		"i10 Sportz 1.1 (LPG)",
		"Accent",
		"Eon Era + (LPG)",
		"Santro Xing GL (CNG)",
		"Accent Executive (LPG)",
		"Eon Magna + (LPG)",
		"Santro Xing GL (LPG)",
		"Santro Xing GLS (LPG)",
		"Santro Xing GLS (CNG)",
		"Santro Xing GL (CNG)",
		"Santro Xing GL (LPG)",
		"Accent Executive (LPG)",
		"Santro Xing GLS (LPG)",
		"Santro Xing GL Plus (LPG)"
	],
	"Chevrolet": ["Sail 1.2 Base",
		"Optra LS 1.6",
		"Sail U-VA 1.2 LS",
		"Beat LS (Petrol)",
		"Aveo U-VA 1.2",
		"Optra SRV 1.6 Opt",
		"Spark LS 1.0 Muzic",
		"Sail U-VA 1.2 LT",
		"Sail 1.2 LS",
		"Enjoy 1.4 LTZ",
		"Aveo U-VA LS 1.2",
		"Optra 1.6",
		"Optra LS AT 1.8",
		"Spark 1.0",
		"Enjoy 1.4 LT",
		"Aveo 1.4 (Petrol)",
		"Optra Magnum LS 1.6",
		"Optra Magnum Max 1.6",
		"Optra LT Royale 1.6",
		"Spark LT 1.0 (Petrol)",
		"Beat PS (Petrol)",
		"Spark LS 1.0 (Petrol)",
		"Beat LT (Petrol)",
		"Sail Hatchback 1.2 LS",
		"Sail Hatchback 1.2 LT",
		"Optra LT AT 1.8",
		"Aveo LT 1.4",
		"Optra LS 1.8",
		"Sail 1.2 LT",
		"Aveo LT 1.6",
		"Aveo U-VA LT 1.2",
		"Optra SRV 1.6",
		"Forester AWD",
		"Optra Elite 1.6",
		"Optra Platinum 1.6",
		"Sail Hatchback 1.2 Base",
		"Enjoy 1.4 LS",
		"Optra LT 1.8",
		"Spark E 1.0",
		"Aveo LS 1.4",
		"Optra Magnum LT 1.6",
		"Spark PS 1.0 (Petrol)",
		"Sail U-VA 1.2 Base",
		"Captiva LTZ AWD 2.2",
		"Enjoy 1.3 LS",
		"Optra Magnum LS 2.0 TCDi",
		"Sail 1.3 Base",
		"Sail U-VA 1.3 LT",
		"Sail U-VA 1.3 LS",
		"Beat LS (Diesel)",
		"Enjoy 1.3 LT",
		"Cruze LTZ",
		"Beat PS (Diesel)",
		"Sail Hatchback 1.3 LS",
		"Sail Hatchback 1.3 LT",
		"Tavera Neo 3 Max",
		"Cruze LT",
		"Cruze LTZ AT",
		"Sail U-VA 1.3 Base",
		"Beat LT (Diesel)",
		"Sail 1.3 LS",
		"Sail 1.3 LT",
		"Captiva LTZ AWD AT",
		"Optra Magnum MAX 2.0 TCDi",
		"Trailblazer LTZ AT",
		"Optra Magnum LT 2.0 TCDi",
		"Captiva LTZ AWD Xtreme",
		"Sail Hatchback 1.3 Base",
		"Enjoy 1.3 LTZ",
		"Tavera Neo 3 LS",
		"Tavera Neo 3 LT",
		"Captiva LT",
		"Beat LS (LPG)",
		"Beat LT (LPG)",
		"Spark LS 1.0 (LPG)",
		"Spark LT 1.0 (LPG)",
		"Spark PS 1.0 (LPG)",
		"Beat LS (LPG)",
		"Beat LT (LPG)",
		"Spark LT 1.0 (LPG)",
		"Spark LS 1.0 (LPG)",
		"Aveo 1.4 (CNG)",
		"Spark PS 1.0 (LPG)",
		"Beat LT (LPG)",
		"Beat LS (LPG)"
	],
	"Mahindra": ["KUV100 K4+ (Petrol)",
		"KUV100 K2+ (Petrol)",
		"Verito 1.4 G2",
		"KUV100 K2 (Petrol)",
		"KUV100 K4 (Petrol)",
		"KUV100 K6 (Petrol)",
		"KUV100 K6+ (Petrol)",
		"KUV100 K8 (Petrol)",
		"Verito 1.4 G4",
		"Bolero EX AC",
		"Bolero Plus I",
		"KUV100 K6 (Diesel)",
		"Verito 1.5 D2",
		"XUV500 Sportz Ltd",
		"XUV500 Sportz Ltd",
		"KUV100 K4+ (Diesel)",
		"Scorpio Getaway 2WD",
		"Scorpio Getaway 2WD",
		"Bolero SLE",
		"Xylo E2",
		"Xylo E9",
		"Bolero ZLX I",
		"KUV100 K8 (Diesel)",
		"Verito Vibe CS 1.5 D6",
		"Scorpio DX 2.6 Turbo 7 Seater",
		"Xylo E4",
		"Xylo E8",
		"Scorpio VLX Special Edition",
		"Scorpio VLX 4WD Airbag AT 8 Seater",
		"KUV100 K6+ (Diesel)",
		"Scorpio S2",
		"XUV500 W6",
		"XUV500 W8",
		"Scorpio DX 2.6 Turbo 8 Seater",
		"Scorpio Ex",
		"Scorpio VLX 2WD",
		"Bolero DI AC I",
		"Bolero Plus AC",
		"KUV100 K2+ (Diesel)",
		"Scorpio S4 Plus",
		"TUV300 T8",
		"Scorpio 2.6 Turbo 7 Seater",
		"Scorpio LX",
		"Bolero DI 4WD I",
		"Bolero DI I",
		"Bolero LX 4WD",
		"Quanto C2",
		"Quanto C4",
		"Scorpio S10 4WD AT",
		"Scorpio S6 Plus",
		"Thar DI 4WD",
		"Verito 1.5 D4",
		"Verito 1.5 D6",
		"Bolero VLX CRDe",
		"Scorpio VLX 4WD Airbag 7 Seater",
		"Bolero Plus AC I",
		"Scorpio DX 2.6 Turbo 8 Seater",
		"Xylo Celebration Edition",
		"Scorpio S10 4WD",
		"TUV300 T6",
		"Verito Vibe CS 1.5 D2",
		"Scorpio Getaway 4WD",
		"Scorpio S10 4WD AT",
		"Thar CRDe 4x4 AC",
		"XUV500 W4",
		"XUV500 W8 AWD",
		"Scorpio M2DI",
		"Scorpio LX 2.6 Turbo",
		"Scorpio VLS 2.2 mHawk",
		"Scorpio Ex",
		"Scorpio VLX 2WD",
		"Quanto C6",
		"Scorpio S10",
		"Verito Vibe CS 1.5 D4",
		"XUV500 W10",
		"XUV500 W10 AT",
		"Xylo H4",
		"Bolero SLX 4WD",
		"Bolero XL 9 Seater",
		"Bolero SLX 2WD",
		"Scorpio VLX 2WD Airbag",
		"XUV500 Xclusive",
		"Bolero EX",
		"Bolero Plus AC I",
		"Scorpio S4",
		"XUV500 W8 AWD",
		"Bolero Diz",
		"Xylo H8",
		"Scorpio SLE 2.6 CRDe",
		"KUV100 K4 (Diesel)",
		"XUV500 W10 AWD",
		"XUV500 W10 AWD AT",
		"Xylo D2",
		"Bolero LX 4WD",
		"Scorpio S4 Plus",
		"Scorpio S8",
		"Bolero XL 7 Seater",
		"Bolero XL 7 Seater",
		"Bolero Plus AC PS",
		"Scorpio SLX 2.6 Turbo 7 Seater",
		"Scorpio VLS AT 2.2 mHawk",
		"Scorpio 2.6 Turbo 9 Seater",
		"Scorpio 2.6 Turbo 9 Seater",
		"Scorpio DX 2.6 Turbo 7 Seater",
		"Scorpio VLX 2WD AT",
		"Scorpio VLX 4WD",
		"Scorpio LX",
		"Scorpio SLE",
		"Scorpio VLX 2WD Airbag",
		"Thar DI 2WD",
		"XUV500 W8 AT",
		"Scorpio VLX 4WD AT",
		"Bolero Plus I",
		"Quanto C8",
		"TUV300 T4",
		"Xylo D4",
		"Bolero XL10 Seater",
		"Scorpio SLE",
		"Scorpio LX 4WD BS-IV",
		"Scorpio VLX 2WD Airbag AT BS-IV",
		"KUV100 K2 (Diesel)",
		"Xylo E6",
		"Scorpio VLX 4WD Airbag AT 8 Seater"
	],
	"Skoda": ["Octavia Ambiente 1.8 Turbo",
		"Superb 2.8 V6 AT",
		"Octavia Elegance 1.8 TSI AT",
		"Rapid 1.6 MPI Elegance AT",
		"Laura Active 1.8 TSI",
		"Rapid 1.6 MPI Ambition",
		"Rapid Active 1.6 MPI MT",
		"Laura Ambition 1.8 TSI",
		"Fabia Elegance 1.2MPI",
		"Octavia Combi RS",
		"Superb 3.6 FSI 4x4",
		"Superb Ambition 1.8 TSI",
		"Octavia 1.4 TSI Ambition",
		"Fabia Ambition Plus 1.2 MPI",
		"Laura RS",
		"Fabia Scout Scout 1.2 TDI",
		"Rapid Ambition 1.6 MPI AT Plus",
		"Laura Ambiente 1.8 TSI",
		"Octavia 1.8 TSI AT Style Plus",
		"Fabia Classic 1.2 MPI",
		"Fabia Ambiente 1.2 MPI",
		"Fabia Ambition 1.2 MPI",
		"Rapid Leisure 1.6 MPI AT",
		"Octavia Active 1.4 TSI",
		"Rapid 1.6 MPI Style AT",
		"Fabia Elegance 1.6 MPI",
		"Rapid Ambition 1.6 MPI MT",
		"Rapid 1.6 MPI Elegance",
		"Rapid 1.6 MPI Active",
		"Octavia Rider 1.8 Turbo",
		"Laura Classic 1.8 TSI",
		"Rapid 1.6 MPI Style Plus",
		"Rapid 1.6 MPI Style Plus AT",
		"Fabia Active 1.2 MPI",
		"Octavia RS 1.8 Turbo",
		"Octavia Rider 2.0 MPI",
		"Rapid 1.6 MPI Elegance Plus AT",
		"Rapid Leisure 1.6 MPI MT",
		"Rapid Elegance 1.6 MPI AT",
		"Rapid 1.6 MPI Elegance Plus",
		"Rapid 1.6 MPI Ambition Plus AT",
		"Fabia Scout Scout 1.2 MPI",
		"Octavia Elegance 2.0 MPI",
		"Superb Elegance 1.8 TSI",
		"Fabia Ambiente 1.4 PD TDI",
		"Fabia Scout Scout 1.2 TDI",
		"Fabia Classic 1.2 TDI",
		"Octavia Active 2.0 TDI CR",
		"Fabia Classic 1.4 PD TDI",
		"Fabia Classic 1.2 TDI",
		"Fabia Ambition Plus 1.2 TDI CR",
		"Rapid 1.5 TDI CR Ambition Plus",
		"Rapid 1.5 TDI CR Elegance Plus",
		"Laura Ambiente 2.0 TDI CR",
		"Rapid 1.5 TDI CR Style Plus",
		"Laura L&K 1.9 PD AT",
		"Fabia Ambiente 1.2 TDI",
		"Rapid Prestige Ambition 1.6 TDI CR MT Plus",
		"Rapid Leisure 1.6 TDI CR MT Plus",
		"Octavia 2.0 TDI CR AT Ambition",
		"Fabia Ambition 1.2 TDI",
		"Laura Ambition 2.0 TDI CR",
		"Octavia Rider AT 1.9 TDI",
		"Rapid Elegance 1.6 TDI CR MT",
		"Yeti Style 4x2",
		"Yeti Style 4x4",
		"Octavia L&K",
		"Octavia Combi L&K",
		"Laura Ambiente 1.9 TDI",
		"Laura Elegance 2.0 TDI CR",
		"Octavia Elegance 2.0 TDI AT",
		"Superb 2.0 TDI PD",
		"Yeti Elegance 4 X 2",
		"Superb Elegance TDI AT",
		"Octavia Elegance 1.9 TDI",
		"Laura Elegance 1.9 TDI",
		"Octavia 2.0 TDI CR Ambition",
		"Fabia Active 1.4 PD TDI",
		"Laura L&K 1.9 PD",
		"Fabia Elegance 1.2 TDI",
		"Fabia Active 1.2 TDI",
		"Yeti Elegance 4 X 4",
		"Rapid 1.5 TDI CR Elegance",
		"Superb 2.5 TDI AT",
		"Rapid 1.5 TDI CR Ambition AT",
		"Fabia Elegance 1.4 PD TDI",
		"Octavia Elegance AT 1.9 TDI",
		"Fabia Elegance 1.2 TDI",
		"Superb Ambition 2.0 TDI CR AT",
		"Octavia 2.0 TDI CR AT Style Plus",
		"Fabia Ambiente 1.2 TDI",
		"Rapid 1.5 TDI CR Elegance Plus AT",
		"Fabia Elegance 1.2MPI",
		"Rapid Ambition 1.6 TDI CR MT",
		"Rapid 1.5 TDI CR Elegance AT",
		"Rapid 1.5 TDI CR Active",
		"Octavia 1.9 TDI",
		"Rapid Active 1.6 TDI CR MT",
		"Rapid 1.5 TDI CR Ambition",
		"Rapid 1.5 TDI CR Style Plus AT",
		"Octavia Rider 1.9 TDI",
		"Octavia Ambiente 1.9 TDI",
		"Rapid 1.5 TDI CR Ambition Plus AT"
	],
	"Nissan": ["Teana 230JM",
		"Micra X Shift",
		"Micra XL CVT",
		"Teana MID",
		"Sunny XV",
		"Terrano XL (Petrol)",
		"Teana UPPER",
		"Micra XV (Petrol)",
		"370Z Touring Coupe",
		"Micra XL (Petrol)",
		"Sunny XE",
		"Micra XV CVT",
		"Sunny XL",
		"Micra XE (Petrol)",
		"Micra Active XL",
		"Micra Active XV",
		"X-Trail LE",
		"Evalia SV",
		"Micra XV (Diesel)",
		"Sunny XL D",
		"Sunny XV D",
		"Evalia XE",
		"X-Trail Comfort",
		"X-Trail X-Pecial",
		"Evalia XL",
		"Micra XE (Diesel)",
		"X-Trail Elegance",
		"Micra XL (Diesel)",
		"Sunny XE D",
		"Evalia XV",
		"Terrano XE (Diesel)",
		"Terrano XL (Diesel)",
		"X-Trail SLX"
	],
	"Volvo": ["S60 T6",
		"V40 Cross Country T4 Momentum",
		"XC90 3.2 AWD",
		"S80 3.2",
		"S80 V8 AWD",
		"XC90 V8 AWD",
		"XC60 Summum D4",
		"S80 Kinetic D4",
		"S60 Kinetic D4",
		"S80 Summum D4",
		"XC60 Kinetic",
		"XC90 Inscription Luxury",
		"S60 Momentum",
		"S60 Summum D5",
		"S60 Kinetic D5",
		"XC60 D5 AWD AT",
		"S60 Inscription",
		"XC60 Inscription",
		"V40 D3 Kinetic",
		"V40 D3 R-Design",
		"V40 Cross Country D3 Inscription",
		"S60 Kinetic",
		"S60 Summum D3",
		"S60 Kinetic D3",
		"S80 Summum D5",
		"XC90 Momentum Luxury",
		"S60 Summum D4",
		"S80 Momentum",
		"XC60 Momentum",
		"S80 Inscription",
		"XC60 Kinetic D4",
		"XC90 D5 AWD"
	],
	"Land Rover": ["Range Rover Evoque Dynamic Si4 Coupe",
		"Range Rover Sport V8 SC SVR",
		"Range Rover 5.0 Supercharged V8",
		"Range Rover Sport 5.0 V8",
		"Range Rover LWB 5.0 V8 Autobiography",
		"Range Rover Sport V8 SC Autobiography",
		"Freelander 2 S",
		"Range Rover Sport SDV6 HSE",
		"Range Rover LWB 4.4 SDV8 Autobiography",
		"Freelander 2 Sterling Edition",
		"Freelander 2 HSE",
		"Range Rover Evoque SE",
		"Discovery SE",
		"Discovery Sport HSE",
		"Range Rover Evoque Dynamic SD4",
		"Range Rover LWB 4.4 SDV8 Vogue SE",
		"Discovery 4 3.0L TDV6 SE",
		"Range Rover LWB 3.0 V6 Vogue",
		"Discovery Sport SE",
		"Range Rover Sport SDV6 SE",
		"Range Rover 3.6 TDV8 Vogue SE",
		"Range Rover Evoque HSE Dynamic",
		"Range Rover Evoque Pure SD4",
		"Range Rover Evoque Prestige SD4",
		"Range Rover Evoque HSE",
		"Discovery HSE",
		"Freelander 2 SE",
		"Range Rover Sport 3.6 TDV8",
		"Discovery Sport S",
		"Range Rover Sport SDV6 S",
		"Range Rover Evoque Pure",
		"Discovery 3 TDV6 Automatic",
		"Range Rover Sport 3.0 TDV6 HSE"
	],
	"Audi": ["R8 5.2 V10 Spyder",
		"A6 3.2 FSI Quattro",
		"Q7 4.2 FSI Quattro",
		"Q3 2.0 TFSI Quattro",
		"A6 35 TFSI Premium",
		"TT 45 TFSI",
		"S5 Sportback 3.0 TFSI Quattro",
		"RS5 4.2 Coupe",
		"A6 S6 4.0 TFSI",
		"R8 4.2 V8 Coupe",
		"R8 5.2 V10 Coupe",
		"A8 L 60 TFSI",
		"R8 5.2 V10 Plus",
		"Q5 2.0 TFSI Quattro",
		"A6 35 TFSI Premium",
		"RS7 Sportback 4.0 TFSI Quattro",
		"A6 3.0 I Multitronic",
		"A8 L 6.0 W12 Quattro",
		"TT 3.2 Coupe Quattro",
		"A4 3.2 FSI Quattro",
		"R8 Coupe 4.2 FSI Quattro",
		"A3 40 TFSI Premium Plus",
		"A4 2.0 TFSI",
		"A4 2.0 TFSI",
		"A6 3.2 FSI Quattro",
		"A6 2.0 TFSi Premium",
		"A3 Cabriolet 40 TFSI",
		"A3 Cabriolet 40 TFSI",
		"A6 2.8 FSI",
		"A6 3.0 I Multitronic",
		"A6 2.0 TFSi Technology Pack",
		"Q7 3.0 TFSI Quattro",
		"A4 35 TFSI Premium",
		"A6 35 TFSI",
		"RS6 Avant",
		"TT 2.0 TFSI Quattro",
		"A8 L W12",
		"Q7 3.6 FSI Quattro",
		"A4 1.8 T Multitronic",
		"A4 1.8 TFSI",
		"A6 3.0 TFSI Quattro",
		"A8 L 60 TDI",
		"A6 2.7 TDI",
		"Q3 2.0 TDI S Edition",
		"A4 35 TDI Technology Pack",
		"A6 35 TDI",
		"A8 L 50 TDI",
		"Q3 2.0 TDI Quattro Dynamic",
		"Q7 4.2 TDI Quattro",
		"A3 35 TDI Attraction",
		"Q3 35 TDI Premium",
		"A6 35 TDI Technology",
		"Q7 45 TDI Premium Plus",
		"A6 2.0 TDI Premium",
		"A3 35 TDI Premium",
		"A4 2.0 TDI Multitronic",
		"Q7 3.0 TDI Quattro Premium",
		"Q5 30 TDI Technology",
		"A4 3.0 TDI Quattro",
		"A3 35 TDI Premium Plus",
		"Q7 45 TDI Technology Pack",
		"Q7 3.0 TDI Quattro Technology Pack",
		"A4 35 TDI Premium",
		"Q5 30 TDI Premium",
		"Q5 3.0 TDI Quattro",
		"Q5 2.0 TDI Quattro",
		"Q3 2.0 TDI Base Grade",
		"A6 2.0 TDI Technology Pack",
		"A6 3.0 TDI Quattro",
		"A4 35 TDI Premium Sport",
		"A3 35 TDI Technology",
		"A6 3.0 TDI Quattro Technology Pack",
		"Q3 30 TDI S",
		"A8 L 3.0 TDI Quattro",
		"Q3 2.0 TDI Quattro Premium",
		"A6 35 TDI Premium",
		"A7 Sportback 3.0 TDI Quattro"
	],
	"BMW": ["X5 M",
		"5 Series 525i",
		"6 Series M6 Gran Coupe",
		"4 Series M4 Coupe",
		"3 Series 320i",
		"X6 xDrive 50i",
		"7 Series 740Li",
		"M5",
		"X1 sDrive18i",
		"X3 2.5si",
		"7 Series Active Hybrid",
		"X6 M Coupe",
		"5 Series 520i",
		"X5 xDrive 50i",
		"3 Series 330i",
		"6 Series 650i",
		"M3",
		"3 Series 325i Sedan",
		"3 Series M3 Sedan",
		"7 Series 750Li",
		"6 Series Coupe",
		"5 Series 530i",
		"X5 4.8i",
		"Z4 sDrive 35i",
		"7 Series 760Li",
		"i8 1.5",
		"5 Series M5",
		"5 Series 523i",
		"6 Series Convertible",
		"3 Series GT 320d",
		"X1 sDrive20d",
		"5 Series GT 530d",
		"3 Series 320d",
		"3 Series 320d Highline Sedan",
		"5 Series 520d",
		"7 Series 730Ld",
		"1 Series 118d",
		"6 Series 640d",
		"X3 xDrive20d",
		"X5 3.0d",
		"X6 xDrive 40d",
		"5 Series 530d",
		"5 Series 525d",
		"X6 xDrive 30d",
		"X3 xDrive30d"
	],
	"Honda": ["Amaze 1.2 E i-VTEC",
		"Amaze 1.2 EX i-VTEC",
		"Brio V MT",
		"Accord 2.4 Inspire AT",
		"City 1.5 E MT",
		"City ZX VTEC Plus",
		"City ZX EXi",
		"City ZX VTEC",
		"Brio VX AT",
		"City 1.5 V AT Exclusive",
		"City ZX CVT",
		"Jazz X",
		"City V MT AVN",
		"Mobilio E i-VTEC",
		"Amaze 1.2 VX i-VTEC",
		"City 1.5 V MT Exclusive",
		"Civic Hybrid",
		"Amaze 1.2 S i-VTEC",
		"Brio VX MT",
		"Jazz S MT",
		"Mobilio V i-VTEC",
		"Brio V AT",
		"Brio SAT",
		"City 1.5 S AT",
		"CR-V 2.4 AT",
		"City V (Petrol)",
		"City VX (Petrol)",
		"Accord 2.4 Elegance MT",
		"Amaze 1.2 SX i-VTEC",
		"Jazz V AT",
		"Brio SMT",
		"Jazz Base",
		"Jazz Active",
		"Amaze 1.2 VX AT i-VTEC",
		"Brio E MT",
		"Brio EX MT",
		"City VX AT (Petrol)",
		"Jazz SV MT",
		"Mobilio S i-VTEC",
		"City 1.5 S MT",
		"Civic 1.8V MT",
		"City SV AT (Petrol)",
		"Accord 2.4 VTi-L MT",
		"Accord 2.4 AT",
		"City 1.5 V AT",
		"Civic Sport",
		"City 1.5 Corporate MT",
		"Jazz E MT",
		"City 1.5 EXi New",
		"CR-V 2.4 MT",
		"City E (Petrol)",
		"City SV (Petrol)",
		"CR-V 2.4L 4WD AVN",
		"City S (Petrol)",
		"Civic 1.8V AT",
		"Civic 1.8E MT",
		"Amaze 1.2 S AT i-VTEC",
		"Amaze 1.2 S Plus i-VTEC",
		"City VX MT (Petrol)",
		"CR-V 2.0L 2WD AT",
		"CR-V 2.0L 2WD MT",
		"Jazz S AT",
		"Accord 2.4 VTi-L AT",
		"Accord 2.4 Inspire MT",
		"Jazz S",
		"Jazz V MT",
		"Accord 2.4 Elegance AT",
		"Accord 3.5 V6 Inspire",
		"City 1.5 V MT",
		"City ZX GXi",
		"City V AT AVN",
		"Brio S MT",
		"Jazz VX MT",
		"Civic 1.8S AT",
		"Civic 1.8S MT",
		"Accord 3.0 V6 AT",
		"Accord 3.0 V6 AT",
		"Accord 2.4 MT",
		"Accord 3.5 V6",
		"Jazz Select Edition",
		"Jazz Mode",
		"Jazz Select",
		"City SV (Diesel)",
		"Amaze 1.5 E i-DTEC",
		"Mobilio E i-DTEC",
		"Jazz SV iDTEC",
		"City S (Diesel)",
		"City SV (Diesel)",
		"Mobilio V i-DTEC",
		"City E (Diesel)",
		"City SV (Diesel)",
		"City V (Diesel)",
		"Mobilio RS i-DTEC",
		"Mobilio S i-DTEC",
		"Amaze 1.5 VX i-DTEC",
		"Jazz S iDTEC",
		"Jazz E iDTEC",
		"Amaze 1.5 SX i-DTEC",
		"City VX MT (Diesel)",
		"Amaze 1.2 E i-VTEC",
		"Amaze 1.5 EX i-DTEC",
		"City VX (Diesel)",
		"Jazz V iDTEC",
		"Jazz VX iDTEC",
		"Amaze 1.5 S i-DTEC",
		"Amaze 1.5 SX i-DTEC",
		"City V MT Compatible",
		"Amaze 1.2 S Plus i-VTEC",
		"City V MT Compatible"
	],
	"Mercedes-Benz": ["S-Class S 63 AMG",
		"M-Class M Guard",
		"C-Class 180 Elegance MT",
		"E-Class 240 V6 AT",
		"CLS 350 BlueEFFICIENCY",
		"E-Class E 63 AMG",
		"C-Class 200 K AT",
		"A-Class A 180 Sport Petro",
		"GLA-Class 45 AMG 4MATIC",
		"S-Class 350",
		"C-Class 200 K MT",
		"E-Class 280 Elegance",
		"A-Class A 180",
		"M-Class ML 63 AMG",
		"CLA-Class 200 Sport",
		"S-Class S 500",
		"E-Class E350",
		"CLS-Class 350",
		"S-Class Maybach S 600",
		"S-Coupe S 500 4MATIC",
		"C-Class 180 Classic",
		"C-Class 63 AMG",
		"GL 500",
		"SLK-Class SLK 200 K",
		"GLA-Class 200 Sport",
		"C-Class Grand Edition",
		"S-Class Maybach S 500",
		"B-Class B180",
		"C-Class 200 CGI",
		"E-Class Cabriolet E 400 Cabriolet",
		"GLE Coupe 450 AMG",
		"CLS 63 AMG",
		"E-Class E250 Elegance",
		"M-Class 350",
		"SLK-Class SLK 55 AMG",
		"C-Class 250 Avantgarde",
		"CLS 500",
		"S-Class S Guard",
		"C-Class 200 K Elegance AT",
		"E-Class 240 V6 MT",
		"R-Class R350 4MATIC",
		"GL-Class 63 AMG",
		"S-Coupe S 63 AMG",
		"C-Class 230 Avantgarde",
		"CLA-Class 45 AMG",
		"SLK-Class SLK 350",
		"SL 350",
		"E-Class E200",
		"SLS AMG Coupe",
		"AMG GT S",
		"E-Class 200 K Classic",
		"A-Class A 200d",
		"C-Class 220 CDI AT",
		"E-Class E250 CDI Classic",
		"C-Class 220 BlueEfficiency",
		"C-Class 200 CDI Elegance",
		"GL 3.0 Grand Edition Executive",
		"GL 3.0 Grand Edition Luxury",
		"E-Class E250 CDI Launch Edition",
		"GLA-Class 200 CDI",
		"GLE-Class 350 d",
		"E-Class E220 CDI Blue Efficiency",
		"E-Class E350 CDI BlueEfficiency",
		"A-Class Edition 1",
		"E-Class E 350 CDI Avantgarde",
		"E-Class 270 CDI",
		"S-Class S 350 CDI",
		"B-Class B 200 CDI",
		"CLA-Class 200 CDI",
		"E-Class E 250 CDI Avantgarde",
		"CLS-Class 250 CDI",
		"GL-Class 350 CDI",
		"C-Class 200 CDI Classic",
		"E-Class E350 CDI Avantgarde",
		"C-Class Grand Edition CDI",
		"R-Class R350 CDI 4Matic",
		"C-Class 220 CDI MT",
		"E-Class 220 CDI Sport",
		"C-Class Edition C",
		"C-Class 250 CDI Classic",
		"A-Class A 200 CDI",
		"A-Class A 180 CDI Style",
		"C-Class 250 CDI Avantgarde",
		"C-Class 250 CDI Elegance",
		"B-Class Edition 1",
		"E-Class 280 CDI Elegance",
		"M-Class 350 CDI",
		"C-Class 250 CDI",
		"GLE-Class 250 d",
		"E-Class E250 CDI BlueEfficiency",
		"B-Class B180 CDI"
	],
	"Bentley": ["Azure Convertible",
		"Mulsanne V8",
		"Continental GT Coupe",
		"Continental GTC V8S",
		"Continental Flying Spur V8",
		"Continental GT V8",
		"Arnage RL",
		"Continental GTC Speed",
		"Continental GT Speed",
		"Continental GT V8S",
		"Arnage R",
		"Continental GTC V8",
		"Continental Flying Spur W12",
		"Continental GTC Convertible"
	],
	"Porsche": ["911 Carrera Cabriolet",
		"911 Carrera S",
		"911 Carrera 4S Cabriolet",
		"Panamera S E – Hybrid",
		"Cayenne S (Petrol)",
		"911 Turbo",
		"Cayenne GTS",
		"Panamera Base",
		"911 GT3",
		"911 Carrera",
		"911 Targa 4",
		"911 Targa 4S",
		"911 Carrera 4",
		"911 Turbo S",
		"Cayenne S Hybrid",
		"Boxster GTS",
		"Boxster S Tiptronic",
		"Cayenne Base",
		"Cayman GTS",
		"Macan Turbo",
		"911 Carrera 4 Cabriolet",
		"Cayenne Turbo",
		"911 Carrera 4S",
		"Cayman S Tiptronic",
		"911 Carrera S Cabriolet",
		"Macan S (Diesel)",
		"Panamera GTS",
		"Panamera",
		"Panamera 4",
		"Cayenne",
		"Cayenne S (Diesel)"
	],
	"Ferrari": ["911 Carrera 4 Cabriolet",
		"Cayenne Turbo",
		"911 Carrera 4S",
		"Cayman S Tiptronic",
		"911 Carrera S Cabriolet",
		"Macan S (Diesel)",
		"Panamera GTS"
	],
	"Jaguar": ["Panamera",
		"Panamera 4",
		"Cayenne",
		"Cayenne S (Diesel)",
		"F-Type V6 S Convertible",
		"XK RS",
		"XJ L 3.0 V6",
		"F-Type S Coupe",
		"XJ L 5.0 V8",
		"XK R V8 Coupe",
		"XJ L 2.0 L Portfolio",
		"F-Type Coupe",
		"F-Type V8 S Convertible",
		"F-Type R Coupe",
		"XK V8 Coupe Spl",
		"XF V8",
		"XF 2.0",
		"XJ L 3.0",
		"XF S V6",
		"XJ L 3.0 V6 premium-luxury",
		"XJ L 3.0 V6 Portfolio",
		"XF Aero-sport",
		"XF 2.2"
	],
	"Lamborghini": ["Huracan LP 610-4",
		"Aventador LP 700-4",
		"Gallardo LP 560-4",
		"Huracan LP 580-2",
		"Murcielago LP640",
		"Gallardo Spyder"
	],
	"Bugatti": ["Veyron 16.4 Grand Sport"],
	"Maruti Suzuki": ["Celerio ZXi AMT",
		"Ciaz VXi+",
		"SX4 VXi (Petrol)",
		"Wagon R 1.0 LX",
		"800 Std",
		"Alto 800 Vxi",
		"Baleno VXi",
		"Ertiga VXI (Petrol)",
		"Esteem AX",
		"Estilo LXi (998 cc) (Petrol)",
		"Grand Vitara 2.0",
		"Gypsy King ST",
		"Omni 5 Seater",
		"SX4 ZXi",
		"Versa DX 8 Seater",
		"Alto K10 LXi (Petrol)",
		"Alto XCITE",
		"Esteem LX",
		"Estilo LXi (998 cc) (Petrol)",
		"Omni 8 Seater",
		"Omni Cargo (Petrol)",
		"Omni E 8 STR BS-IV",
		"Stingray VXi AMT",
		"Esteem LXi",
		"Baleno Std",
		"Eeco 5 Seater (Petrol)",
		"Ertiga VXI (Petrol)",
		"Estilo LX (998 cc)",
		"Omni Cargo (Petrol)",
		"Ritz Vxi",
		"Swift Dzire LXi",
		"Wagon R LXi",
		"Wagon R VXi",
		"Zen VXi",
		"Alto 800 Lxi (Petrol)",
		"Alto K10 VXi",
		"Ertiga ZXI",
		"Esteem VXi",
		"Grand Vitara 2.4 AT",
		"Grand Vitara XL-7 AT",
		"Gypsy King HT",
		"Kizashi CVT",
		"Ritz Vxi AT",
		"Swift Dzire ZXI",
		"Wagon R 1.0 VXi AMT",
		"Ertiga ZXI",
		"Estilo LX (1061 cc)",
		"Versa DX 5 Seater",
		"Alto LX (Petrol)",
		"A-Star Vxi",
		"Celerio VXi (Petrol)",
		"Estilo Sports",
		"Estilo Vxi (998 cc)",
		"Grand Vitara XL-7 MT",
		"Ritz Lxi",
		"SX4 ZXI AT",
		"A-Star Lxi",
		"Baleno Delta 1.2",
		"Swift Dzire VXI AMT",
		"Zen LXi",
		"Baleno LXi",
		"Celerio LXi",
		"Estilo Vxi (1061 cc)",
		"Grand Vitara 2.0 AT",
		"Kizashi MT",
		"Ritz Zxi",
		"Swift Vxi",
		"Versa DX2 5 Seater",
		"800 AC",
		"800 AC",
		"Alto K10 LX",
		"Baleno Alpha 1.2",
		"Ciaz VXi",
		"Ciaz ZXI+",
		"Grand Vitara 2.4",
		"Versa STD",
		"Wagon R 1.0 LXi (LPG)",
		"800 AC Uniq",
		"800 AC Uniq",
		"Alto Std (Petrol)",
		"Estilo Vxi (1061 cc)",
		"Stingray VXi",
		"Swift GLAM",
		"Alto Lxi (Petrol)",
		"A-Star Zxi",
		"Stingray LXi",
		"Swift Dzire VXi",
		"Versa DX2 8 Seater",
		"Wagon R 1.0 LXi (Petrol)",
		"Wagon R LX",
		"Alto 800 Std (Petrol)",
		"Celerio ZXi",
		"Ertiga VXI AT (Petrol)",
		"Ritz GENUS VXI",
		"Wagon R 1.0 VXi",
		"Celerio VXi AMT",
		"Celerio LXi AMT",
		"Eeco 7 Seater",
		"Ertiga LXI (Petrol)",
		"Ertiga LXI (Petrol)",
		"Ertiga VXI AT (Petrol)",
		"Estilo LX (1061 cc)",
		"Estilo Lxi (1061 cc)",
		"Swift LXi",
		"Wagon R AX",
		"Zen LX",
		"Zen VXi",
		"Alto 800 Lx (Petrol)",
		"Alto K10 VXi AMT",
		"Baleno Sigma 1.2",
		"Baleno Zeta 1.2",
		"Ciaz ZXi",
		"Estilo LX (998 cc)",
		"Estilo Sports",
		"Swift ZXi",
		"Ciaz VDi +",
		"Esteem Di",
		"Swift Dzire ZDI",
		"Celerio LDi",
		"Esteem D",
		"Ritz Ldi",
		"Ritz Ldi",
		"SX4 VDI",
		"Ritz Zdi",
		"Ciaz ZDi",
		"Swift Dzire ZDI AMT",
		"Baleno Delta 1.3",
		"Ciaz VDi",
		"S-Cross Delta 1.6",
		"Swift VDi",
		"Swift ZDi",
		"SX4 ZDI",
		"Ertiga Zdi 7 Seater",
		"Ritz Vdi",
		"S-Cross Alpha 1.3",
		"S-Cross Zeta 1.3",
		"Swift Dzire VDI",
		"Baleno Zeta 1.3",
		"Ertiga Zdi 7 Seater",
		"Swift Dzire LDI",
		"Baleno Sigma 1.3",
		"Ertiga VDI 7STR",
		"Ritz GENUS VDI",
		"S-Cross Sigma 1.3",
		"Ertiga LDi",
		"Ertiga VDI 7STR",
		"Baleno Alpha 1.3",
		"Zen D",
		"Zen D PS",
		"Zen D PS",
		"Celerio ZDi",
		"Ertiga LDi",
		"S-Cross Delta 1.3",
		"Celerio VDi",
		"S-Cross Alpha 1.6",
		"S-Cross Zeta 1.6",
		"Swift LDi",
		"Ciaz ZDi+",
		"Celerio VXi (CNG)",
		"Omni (LPG)",
		"Omni (CNG)",
		"Wagon R Duo LXi",
		"Wagon R Duo LX",
		"Wagon R Duo LX",
		"Omni Cargo (LPG)",
		"800 Duo Std",
		"800 Duo Std",
		"Alto 800 Std (CNG)",
		"Wagon R 1.0 LXi (LPG)",
		"800 Duo AC",
		"800 Duo AC",
		"Omni Cargo (LPG)",
		"Wagon R 1.0 LXi (CNG)",
		"Wagon R Duo LX",
		"Alto K10 LXi (CNG)",
		"Wagon R 1.0 LXi (CNG)",
		"Alto LX (CNG)",
		"Wagon R 1.0 LXi (LPG)",
		"Alto 800 Lx (CNG)",
		"Ertiga LXi (CNG)",
		"Estilo LXi (998 cc) (CNG)",
		"Alto 800 Std (CNG)",
		"SX4 VXi (CNG)",
		"Celerio VXi (CNG)",
		"Alto Lxi (CNG)",
		"Wagon R Duo LXi",
		"Alto 800 Lxi (CNG)",
		"Eeco 5 Seater (CNG)",
		"Omni (CNG)",
		"Alto Std (CNG)",
		"Ertiga VXI (CNG)",
		"Omni (LPG)",
		"SX4 VXi (CNG)",
		"Ertiga LXi (CNG)",
		"Ertiga LXi (CNG)",
		"Alto Lxi (CNG)",
		"Alto Std (CNG)",
		"Alto LX (CNG)",
		"Alto 800 Lx (CNG)",
		"Ertiga VXI (CNG)",
		"Estilo LXi (998 cc) (CNG)",
		"Alto 800 Std (CNG)",
		"Ertiga VXI (CNG)",
		"Wagon R 1.0 LXi (LPG)",
		"Omni (LPG)"
	],
	"Tata": ["Indica V2 Xeta GLS (1396 cc)",
		"Indica V2 Xeta GLS (1193 cc)",
		"Indica Vista Aqua Quadrajet",
		"Indigo Marina GSX",
		"Indigo XL Classic",
		"Indigo eCS GLS (Petrol)",
		"Nano GenX XMA",
		"Zest XMS (Petrol)",
		"Zest XT (Petrol)",
		"Indica V2 Xeta GVS",
		"Indica V2 Xeta eGL",
		"Nano Base",
		"Indica LEi",
		"Indica V2 Xeta GLE (1396 cc)",
		"Indigo CS GLE",
		"Tata Manza Aqua Safire",
		"Indica V2 Xeta GV",
		"Indica V2 Xeta GLX",
		"Indigo GLX",
		"Indigo GLX",
		"Indigo Marina GLE",
		"Indigo eCS GLX",
		"Nano GenX XTA",
		"Indica LSi",
		"Indica V2 Xeta GLG (1396 cc)",
		"Indigo GVE",
		"Indica Vista GLS Safire65",
		"Indigo eCS GLS eMAX",
		"Indica V2 Xeta GVE",
		"Indica Vista Aura Safire",
		"Indigo GSX (1405 cc)",
		"Safari 4x4 Vxi",
		"Indica Vista GLX Safire65",
		"Indica Vista GVX Safire90",
		"Nano LX",
		"Zest XE (Petrol)",
		"Indica LXi",
		"Indigo CS GLS",
		"Indica Vista GVX Safire65",
		"Indica Vista GLX Safire90",
		"Nano GenX XE",
		"Nano GenX XM",
		"Nano Twist XT",
		"Indica V2 Xeta GVG",
		"Indica Vista AURA Safire-90",
		"Safari 4x4 Exi",
		"Indica Vista GZX Safire90",
		"Nano CX",
		"Zest XM (Petrol)",
		"Indigo GLE (1405 cc)",
		"Bolt XE (Petrol)",
		"Indigo Marina LS",
		"Nano Twist XE",
		"Indigo GLS",
		"Indigo XL Grand",
		"Safari 4x2 Exi",
		"Indica V2 Xeta GL (1396 cc)",
		"Indica Vista Terra Safire",
		"Indigo GLE (1405 cc)",
		"Indigo GVS",
		"Tata Manza Aura Safire",
		"Tata Manza Elan Safire",
		"Bolt XM (Petrol)",
		"Nano GenX XT",
		"Indica V2 Xeta GL (1193 cc)",
		"Indica V2 Xeta GLG (1193 cc)",
		"Indica Vista Aqua Safire",
		"Indica Vista Terra Safire-90",
		"Indigo LX Dicor",
		"Indigo eCS GLX",
		"Indica V2 Xeta eGLS (Petrol)",
		"Indica Vista LE Safire",
		"Indica Vista Aura + Safire",
		"Indigo Marina GLS",
		"Bolt XMS (Petrol)",
		"Bolt XT (Petrol)",
		"Indigo eCS GLX eMAX",
		"Indica V2 Xeta GL (1396 cc)",
		"Indica V2 Xeta eGLX",
		"Indigo GV",
		"Indigo CS GLX",
		"Safari 4x2 Vxi",
		"Indica V2 LX",
		"Indigo eCS GLS (Petrol)",
		"Indica V2 Xeta GLE (Petrol)",
		"Indica V2 Xeta eGLE (Petrol)",
		"Indigo Marina GLX",
		"Bolt XMS (Diesel)",
		"Bolt XT (Diesel)",
		"Indica V2 LX",
		"Indigo eCS VX CR4",
		"Movus CX",
		"Indica eV2 LE",
		"Indica V2 DLG",
		"Indica V2 Turbo DLS",
		"Indica V2 DLG Dicor",
		"Indica Vista LE Quadrajet",
		"Indigo CS LE TDI",
		"Indigo CS LS Dicor",
		"Safari 4x2 EX",
		"Indigo eCS LS CR4",
		"Venture EX",
		"Zest XTA",
		"Indica V2 DLE",
		"Indigo CS LS TDI",
		"Safari 4x4 EX",
		"Sumo Spacio Gold",
		"Indica Vista ZX Quadrajet",
		"Indica V2 LS",
		"Zest XMA",
		"Aria Prestige 4X2",
		"Indica Vista Aura Quadrajet",
		"Indica Vista LX TDI",
		"Bolt XE (Diesel)",
		"Sumo Gold CX",
		"Sumo Gold FX",
		"Indica V2 Turbomax DLE",
		"Indigo LX Dicor",
		"Indigo VS",
		"Indigo CS LX Dicor",
		"Safari 4x4 LX",
		"Sumo Victa GX TC",
		"Safari 4x4 GX Dicor",
		"Safari Storme 2.2 EX 4X2",
		"Venture LX",
		"Zest XE (Diesel)",
		"Indigo LX TDI",
		"Indigo Marina SX",
		"Sumo Grande CX",
		"Indica V2 Turbo DLG",
		"Indica V2 Turbomax DLS",
		"Indica Vista Aqua Quadrajet",
		"Indigo Marina LS",
		"Indigo Marina LX",
		"Tata Manza Elan Quadrajet",
		"Indigo eCS LX CR4",
		"Safari 4x2 GX Dicor",
		"Safari 4x4 EX Dicor",
		"Safari Storme 2.2 VX 4x2",
		"Xenon XT EX 4x2",
		"Indigo LS Dicor",
		"Indigo CS LX TDI",
		"Indigo CS LS Dicor",
		"Tata Manza Aura Quadrajet",
		"Safari Storme 2.2 VX 4x4",
		"Sumo Victa DI GX",
		"Indica eV2 L",
		"Indica V2 DL",
		"Indica Vista VX Quadrajet",
		"Indica eV2 LS",
		"Indica V2 LE",
		"Safari 4x2 LX Dicor",
		"Safari 4x2 VX Dicor",
		"Indica V2 Turbo DLX",
		"Sumo Victa EX",
		"Indica Vista LX Quadrajet",
		"Aria Pride 4x4",
		"Indica V2 L",
		"Sumo Gold GX",
		"Venture CX",
		"Zest XM (Diesel)",
		"Aria Prestige 4X4",
		"Indigo V",
		"Indigo XL Grand Dicor",
		"Safari 4x2 LX",
		"Sumo Grande EX",
		"Indica V2 LS",
		"Xenon XT EX 4x4",
		"Zest XMS (Diesel)",
		"Zest XT (Diesel)",
		"Aria Pure 4x2",
		"Indica Vista Terra TDI",
		"Indigo SX",
		"Indigo CS LX Dicor",
		"Sumo Victa LX",
		"Aria Pleasure 4x2",
		"Sumo Gold LX",
		"Indica V2 DLS Dicor",
		"Indigo eCS LE TDI",
		"Safari 4x4 LX Dicor",
		"Indica Vista LS Quadrajet",
		"Safari Storme Explorer Edition",
		"Indica eV2 LS",
		"Indica eV2 LX",
		"Sumo Gold EX",
		"Venture GX",
		"Indica Vista Aqua TDI",
		"Indigo VE",
		"Indigo XL Classic Dicor",
		"Sumo Victa DI CX",
		"Movus LX",
		"Safari 4x2 EX Dicor",
		"Safari 4x4 VX Dicor",
		"Safari Storme 2.2 LX 4x2",
		"Aria Pleasure 4X4",
		"Indica V2 DLS",
		"Tata Manza Aqua Quadrajet",
		"Bolt XM (Diesel)",
		"Indica V2 DLX",
		"Indica Vista Terra Quadrajet",
		"Indigo LS TDI",
		"Sumo Grande GX",
		"Sumo Grande LX",
		"Sumo Victa DI LX",
		"Sumo Victa DI EX",
		"Indica Vista LS TDI",
		"Indica V2 Xeta GLE (LPG)",
		"Indica V2 Xeta eGLS(LPG)",
		"Indica V2 Xeta eGLE(LPG)",
		"Indica V2 Xeta GLS 1.2",
		"Indica V2 Xeta GLS 1.2",
		"Indica V2 Xeta eGLS(LPG)",
		"Indica eV2 GLS eMAX",
		"Indica eV2 GLX eMAX",
		"Indigo eCS GLX eMAX",
		"Nano XM",
		"Indica V2 Xeta GLE (LPG)",
		"Indigo eCS GLS eMAX",
		"Nano emax CX",
		"Nano emax LX",
		"Indigo eCS GLS eMAX",
		"Indigo eCS GLX eMAX"
	],
	"DATSUN": ["GO NXT",
		"Go Plus T",
		"Go Plus A",
		"GO D",
		"GO A",
		"Go Plus D",
		"GO T"
	],
	"FORCE MOTORS": ["Force One EX",
		"Force One SX",
		"Gurkha 4X2",
		"Gurkha 4X4",
		"Force One LX"
	],
	"RENAULT": ["Fluence 2.0 E4",
		"Pulse RxL (Petrol)",
		"Duster RxE",
		"Kwid RXL",
		"Scala RxL (Petrol)",
		"Kwid RXE",
		"Kwid RXT",
		"Kwid STD",
		"Duster RxL",
		"Pulse RxE (Petrol)",
		"Pulse RxZ (Petrol)",
		"Duster 110 PS RxZ",
		"Scala RxZ",
		"Lodgy 85 PS STD",
		"Lodgy 85 PS RxE",
		"Lodgy 110 PS RxL",
		"Duster 85 PS RxL",
		"Fluence 1.5 E2",
		"Fluence 1.5 E4",
		"Pulse RxZ (Diesel)",
		"Duster 85 PS RxE",
		"Scala RxL (Diesel)",
		"Lodgy 85 PS RXL",
		"Koleos 4x4 MT",
		"Koleos 4x4 AT",
		"Duster 110 PS RxL ADVENTURE",
		"Lodgy 85 PS RXZ",
		"Lodgy 110 PS RXZ",
		"Duster 110 PS RxZ Plus",
		"Koleos 4x2 MT",
		"Fluence E4",
		"Fluence Advantage Edition",
		"Duster 110 PS RxL",
		"Duster 110 PS RxZ (Option)",
		"Pulse RxL (Diesel)",
		"Fluence E2",
		"Pulse RxE (Diesel)",
		"Duster 85 PS RxE ADVENTURE"
	],
	"ROLLS-ROYCE": ["Drophead Coupe Convertible",
		"Ghost Extended Wheelbase",
		"Ghost 6.5",
		"Phantom Coupe 6.8 L",
		"Ghost Series II EWB",
		"Ghost Series II 6.6",
		"Phantom Sedan",
		"Phantom EWB",
		"Wraith Sedan"
	],
	"Ssangyong": ["Rexton RX5",
		"Rexton RX6",
		"Rexton RX7"
	],
	"ISUZU": ["MU7 Premium AT",
		"MU7 Base",
		"MU7 High"
	],
	"Ford": ["Figo Aspire Titanium Plus 1.2 Ti-VCT",
		"Figo Duratec ZXI 1.2",
		"Figo Titanium 1.2 Ti-VCT",
		"Fiesta ZXi 1.4",
		"Fiesta Classic LXi 1.6",
		"Mondeo Duratec HE",
		"EcoSport Ambiente 1.5 Ti-VCT",
		"Figo Aspire Trend 1.2 Ti-VCT",
		"Fiesta SXi 1.6",
		"Figo Duratec LXI 1.2",
		"Mondeo Ghia Duratec",
		"Figo Duratec EXI 1.2",
		"Figo Duratec Titanium 1.2",
		"Ikon 1.6 SXi",
		"Figo Trend 1.2 Ti-VCT",
		"Fiesta EXi 1.6",
		"Fiesta Classic SXi 1.6",
		"Classic 1.6 Duratec CLXi",
		"Fusion 1.6",
		"Fiesta Ambiente (Petrol)",
		"Figo Ambiente 1.2 Ti-VCT",
		"Figo Celebration Edition (Petrol)",
		"Fiesta Style MT",
		"Figo Aspire Ambiente 1.2 Ti-VCT",
		"Fiesta ZXi 1.6",
		"Ikon 1.3 EXi",
		"Ikon 1.8 ZXi",
		"Classic 1.6 Duratec LXi",
		"Fiesta Titanium+",
		"Figo Base 1.2 Ti-VCT",
		"Figo Aspire Titanium 1.5 Ti-VCT AT",
		"EcoSport Titanium+ 1.0L EcoBoost",
		"Fusion +",
		"Classic 1.6 Duratec Titanium",
		"EcoSport Trend 1.5 Ti-VCT",
		"Figo Titanium 1.5 Ti-VCT AT",
		"EcoSport Trend+ 1.0L EcoBoost",
		"Fiesta EXI 1.4",
		"Fiesta LE 1.6",
		"Ikon Rocam 1.3",
		"EcoSport Titanium 1.5 Ti-VCT",
		"EcoSport Titanium 1.5 Ti-VCT",
		"Figo Aspire Titanium 1.2 Ti-VCT",
		"Fiesta S 1.6",
		"Fiesta Classic CLXi 1.6",
		"EcoSport Titanium 1.5 Ti-VCT AT",
		"Figo Titanium Plus 1.2 Ti-VCT",
		"Fusion Plus (Petrol)",
		"Ikon 1.3 Flair",
		"EcoSport Titanium 1.0 Ecoboost",
		"EcoSport Titanium 1.5L TDCi",
		"Ikon DuraTorq 1.4 TDCi",
		"Endeavour XLT 4X2",
		"Mondeo Duratorq DI",
		"Figo Base 1.5 TDCi",
		"Figo Duratorq LXI 1.4",
		"Figo Duratorq EXI 1.4",
		"Figo Ambiente 1.5 TDCi",
		"Figo Aspire Ambiente 1.5 TDCi",
		"Figo Aspire Trend 1.5 TDCi",
		"EcoSport Trend+ 1.5L TDCi",
		"Fiesta Classic LXi 1.4 TDCi",
		"Figo Titanium Plus 1.5 TDCi",
		"Figo Aspire Titanium1.5 TDCi",
		"Fiesta Trend",
		"Endeavour XLT TDCi 4x2",
		"Fusion Plus (Diesel)",
		"Figo Trend 1.5 TDCi",
		"Fiesta ZXi 1.4 TDCi",
		"Fusion 1.4 TDCi",
		"Figo Celebration Edition (Diesel)",
		"Figo Titanium1.5 TDCi",
		"Classic 1.4 TDCi Titanium",
		"Fiesta Style",
		"Endeavour Allterrain edition 4x4 AT",
		"Fiesta Ambiente (Diesel)",
		"Fiesta Titanium",
		"Figo Duratorq Titanium 1.4",
		"Fiesta Classic SXi 1.4 TDCi",
		"Figo Duratorq ZXI 1.4",
		"Figo Aspire Titanium Plus 1.5 TDCi",
		"Fiesta Classic CLXi 1.4 TDCi",
		"Classic 1.4 TDCi LXi",
		"Endeavour 3.0L 4X4 AT",
		"Endeavour 3.0L 4x2 AT",
		"Figo Aspire Trend 1.5 TDCi",
		"Figo Aspire Titanium1.5 TDCi",
		"EcoSport Ambiente 1.5L TDCi",
		"EcoSport Trend 1.5L TDCi",
		"Figo Aspire Ambiente 1.5 TDCi",
		"Figo Aspire Titanium Plus 1.5 TDCi",
		"Endeavour 3.0L Thunder+ 4x4",
		"Endeavour Allterrain edition 4x4 AT",
		"EcoSport Titanium+ 1.5L TDCi",
		"Endeavour XLT 4X4",
		"Endeavour Hurricane LE",
		"Endeavour XLT TDCi 4x4",
		"Fiesta SXi 1.4 TDCI",
		"Fiesta EXi 1.4 TDCi",
		"Classic 1.4 TDCi CLXi",
		"Endeavour 2.5L 4x2"
	],
	"MASERATI": ["Quattroporte S 4.7",
		"GranTurismo S 4.7",
		"Quattroporte 4.2",
		"GranTurismo 4.2 V8",
		"Quattroporte GTS",
		"Quattroporte Sport GT 4.7",
		"GranCabrio 4.7 V8",
		"Quattroporte",
		"Ghibli (Diesel)"
	],
	"Mini": ["Cooper Convertible 1.6",
		"Cooper S 1.6",
		"Cooper S",
		"Cooper Countryman one",
		"Cooper Countryman Cooper S",
		"Cooper D 5 Door",
		"Cooper Countryman Cooper D",
		"Cooper D 3 Door"
	],
	"DC": ["Avanti Standard"],
	"Bajaj": ["DB9 Carbon Edition",
		"Stile LS",
		"Stile LX"
	],
	"Toyota": ["Etios Liva G",
		"Innova 2.0 VX 8 Seater",
		"Corolla Altis G (Petrol)",
		"Prius 1.8 Z5",
		"Prius 1.8 Z6",
		"Corolla Altis 1.8 GL",
		"Innova 2.0 G2",
		"Innova 2.0 G3",
		"Innova 2.0 G 8 Seater",
		"Camry W1 MT",
		"Corolla Altis 1.8 Sport",
		"Land Cruiser Prado VX",
		"Corolla H4 1.8G",
		"Etios Liva J",
		"Innova 2.0 GX 8 Seater",
		"Camry 2.5L AT",
		"Etios Liva LE (Petrol)",
		"Corolla Altis Aero Ltd (Petrol)",
		"Corolla Altis 1.8 J(S)",
		"Camry Hybrid",
		"Etios G",
		"Etios J PS",
		"Camry W3 MT",
		"Etios Liva Xclusive (Petrol)",
		"Etios Xclusive (Petrol)",
		"Etios V SP*",
		"Corolla Altis JS",
		"Camry W4 AT",
		"Corolla H3 1.8G",
		"Etios TRD Sportivo Ltd (Petrol)",
		"Innova 2.0 V",
		"Innova 2.0 V",
		"Etios Liva J PS",
		"Camry W2 AT",
		"Etios Liva G SP",
		"Corolla Altis Ltd (Petrol)",
		"Etios V",
		"Etios VX",
		"Innova 2.0 G1",
		"Etios Cross 1.5 V",
		"Corolla HE 1.8J",
		"Corolla H1 1.8J",
		"Corolla H2 1.8E",
		"Etios J",
		"Corolla Altis GL (Petrol)",
		"Etios Cross 1.2 G",
		"Innova 2.0 G4",
		"Etios Liva VX",
		"Corolla H5 1.8E",
		"Etios G SP",
		"Innova 2.0 E",
		"Corolla Altis 1.8 G AT",
		"Corolla Altis VL AT",
		"Etios Liva V SP*",
		"Etios Liva TRD Sportivo (Petrol)",
		"Corolla Altis G AT",
		"Corolla Altis LE (Petrol)",
		"Etios Liva V",
		"Corolla Altis 1.8 J",
		"Corolla Altis 1.8 G",
		"Corolla Altis 1.8 VL AT",
		"Etios Liva TRD Sportivo (Petrol)",
		"Etios Liva JD",
		"Etios Liva VD",
		"Etios Liva VXD",
		"Fortuner 2.5 Sportivo 4x2 MT",
		"Fortuner 3.0 4x4 MT",
		"Innova 2.5 EV PS 7 Seater",
		"Etios Liva VD SP*",
		"Etios VD SP*",
		"Etios VD",
		"Fortuner 2.5 Sportivo 4x2 AT",
		"Fortuner 3.0 4x4 MT",
		"Innova 2.5 E",
		"Corolla Altis J+",
		"Innova 2.5 EV CS 7 Seater",
		"Etios Liva LE (Diesel)",
		"Etios VXD",
		"Qualis FS",
		"Etios Cross 1.4 VD",
		"Etios J PS",
		"Fortuner 3.0 4x2 AT",
		"Etios TRD Sportivo Ltd (Diesel)",
		"Etios GD SP",
		"Innova 2.5 EV MS 8 Seater",
		"Innova Aero Ltd 7 Seater I",
		"Innova 2.0 GX 8 Seater",
		"Corolla Altis Aero Ltd (Diesel)",
		"Etios Cross 1.4 GD",
		"Innova 2.5 G 7 Seater",
		"Innova 2.5 VX 7 Seater",
		"Innova 2.5 EV PS 8 Seater",
		"Innova 2.5 V 7 Seater",
		"Corolla Altis Ltd (Diesel)",
		"Etios VXD Xclusive",
		"Fortuner 3.0 4x2 MT",
		"Fortuner 3.0 4x2 MT",
		"Etios Liva GD SP",
		"Innova 2.5 G1",
		"Innova 2.5 E PS 8 Seater",
		"Innova 2.0 G 8 Seater",
		"Etios JD",
		"Fortuner 3.0 4x2 AT",
		"Fortuner 3.0 4x4 AT",
		"Fortuner 3.0 4x4 AT",
		"Fortuner 3.0 MT",
		"Etios GD",
		"Land Cruiser LC 200 VX",
		"Fortuner 3.0 Ltd",
		"Fortuner 2.5 Sportivo 4x2 MT",
		"Fortuner 2.5 Sportivo 4x2 MT",
		"Innova 2.5 GX 7 Seater",
		"Innova Crysta 2.5 VX",
		"Etios Liva Xclusive (Diesel)",
		"Fortuner 2.5 Sportivo 4x2 AT",
		"Fortuner 2.5 Sportivo 4x2 AT",
		"Innova 2.5 VX 8 Seater",
		"Fortuner 3.0 MT",
		"Innova 2.5 G4 7 Seater",
		"Qualis GS",
		"Corolla Altis J",
		"Corolla Altis LE (Diesel)",
		"Etios Liva GD",
		"Innova 2.5 E 7 Seater",
		"Etios Liva TRD Sportivo (Diesel)",
		"Innova 2.5 ZX 7 Seater",
		"Corolla Altis G (Diesel)",
		"Corolla Altis GL (Diesel)",
		"Innova 2.5 V 7 Seater",
		"Innova 2.5 E 8 Seater",
		"Land Cruiser LC200 VX Standard",
		"Innova 2.5 GX 8 Seater",
		"Fortuner 3.0 Ltd",
		"Innova 2.5 EV MS 7 Seater",
		"Innova 2.5 E MS 8 Seater",
		"Etios Xclusive (Diesel)"
	],
	"Fiat": ["Avventura Dynamic 1.4",
		"Abarth Punto T-Jet 1.4 Abarth",
		"Adventure Sport 1.6",
		"Palio Stile SLX 1.1",
		"Punto Evo Active 1.2",
		"Linea Dynamic 1.4",
		"Palio NV 1.2 Sport",
		"Palio NV 1.6 Sport",
		"Palio NV 1.2 EL",
		"Punto Dynamic 1.2",
		"Punto Evo Emotion 1.4",
		"Punto Active 1.2",
		"Linea T-Jet",
		"Punto Dynamic 1.4",
		"Palio NV 1.2 ELX",
		"Uno ELX 1.2 AC",
		"Avventura Active 1.4",
		"Linea Active 1.4",
		"Uno Trend 1.2 AC",
		"Punto Evo Dynamic 1.2",
		"Palio Stile Sport 1.6",
		"Linea Classic 1.4 L P Classic",
		"Palio Stile SL 1.1",
		"Palio Stile SLE 1.1",
		"Uno EL 1.2",
		"Linea Emotion 1.4",
		"Linea Emotion T-Jet",
		"Punto Emotion 1.4",
		"Abarth 595 Competizione",
		"Punto Emotion 1.2",
		"Avventura Emotion Multijet 1.3",
		"Linea Dynamic 1.3 L Advanced Multijet",
		"500 Sport",
		"Punto Sport",
		"500 Lounge",
		"Punto Emotion 1.3",
		"Linea Classic 1.3 L Multijet Classic",
		"Palio D EL 1.9 PS",
		"Punto Evo Active Multijet 1.3",
		"Punto Evo Sportivo 1.3",
		"Linea Active 1.3 L Advanced Multijet",
		"Linea Emotion 1.3 L Advanced Multijet",
		"Palio Stile SDE 1.3",
		"Palio Stile SDX 1.3",
		"Palio Stile SD 1.3",
		"Palio D ELX 1.9",
		"Punto Evo Dynamic Multijet 1.3",
		"Avventura Active Multijet 1.3",
		"Linea Elegante 1.3 L Advanced Multijet",
		"Linea Emotion 1.3",
		"Punto Active 1.3",
		"Punto Evo Multijet 1.3",
		"Avventura Dynamic Multijet 1.3",
		"Linea Active 1.3",
		"Linea Dynamic 1.3",
		"Punto Dynamic 1.3"
	],
	"Volkswagen": ["Polo Highline1.5L (Diesel)",
		"Polo Highline1.2L (Petrol)",
		"Polo SR 1.2L (Petrol)",
		"Phaeton 3.6L",
		"Vento Highline (Petrol)",
		"Vento IPL Edition",
		"Polo Trendline 1.2L (Petrol)",
		"Polo GT TSI",
		"Polo Comfortline 1.2L (Petrol)",
		"Vento Style (Petrol)",
		"Beetle 2.0 AT",
		"Jetta Trendline 1.6",
		"Polo Highline 1.6L (Petrol)",
		"Vento Comfortline AT (Petrol)",
		"Vento Highline AT (Petrol)",
		"Polo Trendline 1.2L (Petrol)",
		"Cross Polo 1.2 MPI",
		"Vento Comfortline (Petrol)",
		"Vento Trendline (Petrol)",
		"Beetle 1.4 TSI",
		"Vento TSI",
		"Passat 1.8L TSI",
		"Touareg 3.0 V6 TDI",
		"Vento Style (Diesel)",
		"Polo Highline1.5L (Diesel)",
		"Cross Polo 1.5 TDI",
		"Polo Comfortline 1.5L (Diesel)",
		"Polo GT TDI (1598cc)",
		"Passat Highline DSG",
		"Vento Highline AT (Diesel)",
		"Polo Trendline 1.5L (Diesel)",
		"Vento Comfortline (Diesel)",
		"Polo Trendline 1.2L (Diesel)",
		"Passat 2.0 PD DSG",
		"Jetta Highline TDI",
		"Vento Comfortline AT (Diesel)",
		"Vento Highline (Diesel)",
		"Passat Trendline MT",
		"Vento Trendline (Diesel)",
		"Polo Highline1.2L D",
		"Polo GT TDI (1498cc)",
		"Polo Comfortline 1.2L (Diesel)",
		"Passat Comfortline DSG",
		"Polo Trendline 1.2L (Diesel)"
	],
	"Mitsubishi": ["Cedia Sports",
		"Lancer LXi 1.5",
		"Lancer Evolution X",
		"Cedia Spirit",
		"Cedia Elegance",
		"Outlander 2.4 MIVEC",
		"Outlander 2.4 Chrome Ltd",
		"Cedia Select",
		"Montero 3.2 GLS",
		"Montero 3.2 DI-D AT",
		"Pajero Sport 2.5 MT",
		"Montero 3.2 DI-D MT",
		"Pajero GLX 2.8 CRZ",
		"Challenger 2.8",
		"Lancer LXd 2.0",
		"Pajero Sport 2.5 AT",
		"Pajero SFX 2.8",
		"Cedia Select ALPG",
		"Cedia Spirit ALPG"
	]
};